const API_URL = "http://api.divinedrop.local";
const scripts = [
	"/js/uid.js",
	"/js/utilities.js",
	"/js/tooltipper.js",
	"/js/lit-html.js",
	"/js/idb-manager.js",
	"/js/auth.js",
	"/js/account.js",
	"/js/admin.js",
	"/js/pubsub.js",
	"/js/card-text.js",
	"/js/deck.js",
	"/js/uuid.js",
];
const stylesheets = [
	"/css/spinner.css",
	"/css/loading.css",
	"/css/app.css",
	"/css/tooltip.css",
	"/css/toaster.css",
	"/css/input.css",
	"/css/buttons.css",
	"/css/checkbox.css",
	"/css/skeleton-wave.css",
	"/css/table.css",
	"/css/data-table.css",
	"/css/user-table.css",
	"/css/full-modal.css",
	"/css/edit-profile-modal.css",
	"/css/card-browser.css",
	"/css/radio.css",
	"/css/select.css",
	"/css/deck-browser.css",
	"/css/deck-drawer.css",
];
